language: php
php:
    - 5.3
    - 5.4
    - 5.5

branches:
    only:
        - master

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar self-update
  - php composer.phar install

script: phpunit
