language: php
php:
    - 5.3
    - 5.4
    - 5.5

branches:
    only:
        - master

before_script:
  - ulimit -n 10000
  - sudo apt-get update
  - composer self-update
  - composer require doctrine/mongodb-odm="1.0.*@dev" --no-update
  - composer require jmikola/geojson="~1.0" --no-update
  - composer install --prefer-source --no-interaction
  - wget http://getcomposer.org/composer.phar

script: phpunit
