language: php
php:
    - 5.3
    - 5.4
    - 5.5

branches:
    only:
        - master

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install --prefer-source
  - bin/composer install --prefer-source

script: phpunit
