language: php
php:
    - 5.3

branches:
    only:
        - master

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --prefer-dist

script: phpunit
